# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  ImageName: 'mymvcapp'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: Docker@1
  displayName: 'Build the Docker image'
  inputs:
    containerregistrytype: 'Container Registry'
    command: 'Build an image'
    dockerFile: '**/Dockerfile'
    imageName: '$(ImageName)'
    includeLatestTag: true
    useDefaultContext: false
    buildContext: '.'
- task: Docker@2
  inputs:
    containerRegistry: 'Azure container connection'
    repository: 'mymvcapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(fbdb3974-f29a-4625-b7fa-2a24ba95750e)'
    appType: 'webAppContainer'
    WebAppName: 'mymvcapp'
    deployToSlotOrASE: true
    ResourceGroupName: 'DefaultResourceGroup-CID'
    SlotName: 'production'
    DockerNamespace: 'mymvcapp.azurecr.io/mymvcapp;latest'
    DockerRepository: 'mymvcapp;latest'