# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mymvcapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mymvcapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_fe21b65333d24b8f9322cb09fa9d048e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a93112f80cc24f269f47bd302221496c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mymvcapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fe21b65333d24b8f9322cb09fa9d048e }}/mymvcapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mymvcapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ec4c06a3378248409990b7928acb584c }}
        images: 'mymvcapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fe21b65333d24b8f9322cb09fa9d048e }}/mymvcapp:${{ github.sha }}'